services:
  - type: web
    name: whatsapp-delegation
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SERVICE_ACCOUNT_FILE
        value: credentials.json
      - key: SPREADSHEET_ID
        sync: false
      - key: TEXT_INPUT_SHEET_ID
        sync: false
      - key: EMPLOYEE_SHEET_ID
        sync: false
      - key: FOLDER_ID
        sync: false
